/*LeetCode 389:Find the Difference
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
*/


import java.util.*;
class q76 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String s = sc.nextLine();
        String t = sc.nextLine();
        q76 obj = new q76();
        char result = obj.findTheDifference(s,t);
        System.out.println(result);
    }
    public char findTheDifference(String s, String t) {
        HashMap<Character,Integer> map = new HashMap<>();
        for(char c : s.toCharArray())
        map.put(c, map.getOrDefault(c,0)+1);
        for(char c : t.toCharArray()){
            if(!map.containsKey(c) || map.get(c)==0)
                return c;
            map.put(c, map.get(c)-1);
        }
        return ' ';
    }
}